/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package UAS;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADVAN
 */
public class JFormTambah extends javax.swing.JFrame {
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        
        try {
            String sql= "select * from karyawan";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2)});
            }
            tblKaryawan.setModel(model);
            for (int i = 0; i < tblKaryawan.getColumnCount(); i++) {
            Class<?> col_class = tblKaryawan.getColumnClass(i);
            tblKaryawan.setDefaultEditor(col_class, null);
        }

        }catch (Exception e){
            
        }}
    /**
     * Creates new form JFromBeranda
     */
 
    
    public JFormTambah() {
        initComponents();
        load_table();
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btDashboard = new javax.swing.JButton();
        btTambahPegawai = new javax.swing.JButton();
        btEditPegawai = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btAbout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        txtNomorTelpon = new javax.swing.JTextField();
        cbJabatan = new javax.swing.JComboBox<>();
        rbLakiLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        btTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 112, 75));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\stafftracker-high-resolution-logo1.png")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/icon/user-profile (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 840, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 120));

        jPanel2.setBackground(new java.awt.Color(65, 140, 105));

        btDashboard.setBackground(new java.awt.Color(65, 140, 105));
        btDashboard.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btDashboard.setText("Dashboard");
        btDashboard.setBorderPainted(false);
        btDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDashboardMouseClicked(evt);
            }
        });
        btDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDashboardActionPerformed(evt);
            }
        });

        btTambahPegawai.setBackground(new java.awt.Color(65, 140, 105));
        btTambahPegawai.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btTambahPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btTambahPegawai.setText("Tambah Pegawai");
        btTambahPegawai.setBorderPainted(false);

        btEditPegawai.setBackground(new java.awt.Color(65, 140, 105));
        btEditPegawai.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btEditPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btEditPegawai.setText("Edit Pegawai");
        btEditPegawai.setBorderPainted(false);
        btEditPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEditPegawaiMouseClicked(evt);
            }
        });

        btHapus.setBackground(new java.awt.Color(65, 140, 105));
        btHapus.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btHapus.setForeground(new java.awt.Color(255, 255, 255));
        btHapus.setText("Hapus Karyawan");
        btHapus.setBorderPainted(false);
        btHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHapusMouseClicked(evt);
            }
        });
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btLogout.setBackground(new java.awt.Color(65, 140, 105));
        btLogout.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setText("Keluar");
        btLogout.setBorderPainted(false);
        btLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLogoutMouseClicked(evt);
            }
        });
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btAbout.setBackground(new java.awt.Color(65, 140, 105));
        btAbout.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btAbout.setForeground(new java.awt.Color(255, 255, 255));
        btAbout.setText("About");
        btAbout.setBorderPainted(false);
        btAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAboutMouseClicked(evt);
            }
        });
        btAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btEditPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btTambahPegawai))
                    .addComponent(btDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btHapus)
                        .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btEditPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btHapus)
                .addGap(41, 41, 41)
                .addComponent(btAbout)
                .addGap(26, 26, 26)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 650));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("Nomor Telpon");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel4.setText("Jabatan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel8.setText("Tanggal Lahir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        txtNama.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 250, -1));

        txtTanggalLahir.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        txtTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalLahirActionPerformed(evt);
            }
        });
        getContentPane().add(txtTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 250, -1));

        txtNomorTelpon.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        getContentPane().add(txtNomorTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 250, -1));

        cbJabatan.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        cbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jabatan", "Direktur", "Admin", "Karyawan", "Manager Proyek", "Akunting", "Pemasaran", "Produksi", "IT Support", "Staf HR", " " }));
        getContentPane().add(cbJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 250, -1));

        buttonGroup1.add(rbLakiLaki);
        rbLakiLaki.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbLakiLaki.setText("Laki-Laki");
        rbLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiLakiActionPerformed(evt);
            }
        });
        getContentPane().add(rbLakiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 240, -1));

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 250, -1));

        btTambah.setBackground(new java.awt.Color(2, 112, 75));
        btTambah.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        btTambah.setForeground(new java.awt.Color(255, 255, 255));
        btTambah.setText("Tambah");
        btTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTambahMouseClicked(evt);
            }
        });
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, 210, 60));

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 290, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 250, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFormLogin.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened
    
    
    
    private void btDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDashboardMouseClicked
        // TODO add your handling code here:
        JFormTambah tambahFrame = new JFormTambah();
        tambahFrame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btDashboardMouseClicked

    
    
    private void btDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDashboardActionPerformed
        // TODO add your handling code here:
        JFormAdmin adminFrame = new JFormAdmin();
        adminFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDashboardActionPerformed

    private void rbLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiLakiActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btTambahActionPerformed
    
    private void bersihkan(){
        txtAlamat.setText(null);
        txtNama.setText(null);
        cbJabatan.setSelectedIndex(0);
        txtNomorTelpon.setText(null);
        txtTanggalLahir.setText(null);
        buttonGroup1.clearSelection();
        txtNama.requestFocus();
    }
    
    private boolean isNumeric(String str) {
    return str.matches("\\d+"); // Hanya true jika string hanya terdiri dari angka
}
    
    private void btTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTambahMouseClicked
        // TODO add your handling code here:
        try {
            String jenisKelamin;
            String nomorTelpon = txtNomorTelpon.getText();
        if (!isNumeric(nomorTelpon)) {
            JOptionPane.showMessageDialog(this, "Nomor telepon hanya boleh berisi angka.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses tambah data jika nomor telepon tidak valid
        }
    if (rbLakiLaki.isSelected()) {
        jenisKelamin = "Laki-laki";
    } else if (rbPerempuan.isSelected()) {
        jenisKelamin = "Perempuan";
    } else {
        jenisKelamin = ""; 
    }
            String sql = "INSERT INTO karyawan (NAMA, JABATAN, ALAMAT, TANGGAL_LAHIR, JENIS_KELAMIN, NO_TELEPON) VALUES ('"+txtNama.getText()+
                    "','"+cbJabatan.getSelectedItem()+
                    "','"+txtAlamat.getText()+
                    "','"+txtTanggalLahir.getText()+
                    "','"+jenisKelamin+
                    "','"+txtNomorTelpon.getText()+
                    "')";
            java.sql.Connection conn = (Connection) Config.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            load_table();
            bersihkan();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btTambahMouseClicked

    private void txtTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalLahirActionPerformed

    private void btEditPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditPegawaiMouseClicked
        // TODO add your handling code here:
        JFormEdit editFrame = new JFormEdit();
        editFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btEditPegawaiMouseClicked

    private void btHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHapusMouseClicked
        // TODO add your handling code here:
        JFormHapus hapusFrame = new JFormHapus();
        hapusFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHapusMouseClicked

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHapusActionPerformed

    private void btLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseClicked
        // TODO add your handling code here:
        JFormLogin loginFrame = new JFormLogin();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLogoutMouseClicked

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAboutMouseClicked
        // TODO add your handling code here:
        JFormAbout aboutFrame = new JFormAbout();
        aboutFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAboutMouseClicked

    private void btAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAboutActionPerformed

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblKaryawanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormTambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormTambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbout;
    private javax.swing.JButton btDashboard;
    private javax.swing.JButton btEditPegawai;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btTambahPegawai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbLakiLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomorTelpon;
    private javax.swing.JTextField txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
