/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package UAS;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADVAN
 */
public class JFormHapus extends javax.swing.JFrame {

    /**
     * Creates new form JFromBeranda
     */
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Membuat semua sel pada tabel tidak dapat diedit
            }
        };
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Jabatan");
        model.addColumn("Alamat");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Nomor Telpon");
        
        try {
            String sql= "select * from karyawan";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tblKaryawan.setModel(model);
        }catch (Exception e){
            
        }}
    
    public JFormHapus() {
        initComponents();
        load_table();
        txtId.setEditable(false);
    }


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btDashboard = new javax.swing.JButton();
        btTambahPegawai = new javax.swing.JButton();
        btEditPegawai = new javax.swing.JButton();
        btHapusKaryawan = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btAbout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cbJabatan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rbLakiLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTanggalLahir = new javax.swing.JTextField();
        txtNomorTelpon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btHapus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 112, 75));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\stafftracker-high-resolution-logo1.png")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/icon/user-profile (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 843, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 120));

        jPanel2.setBackground(new java.awt.Color(65, 140, 105));

        btDashboard.setBackground(new java.awt.Color(65, 140, 105));
        btDashboard.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btDashboard.setText("Dashboard");
        btDashboard.setBorderPainted(false);
        btDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDashboardMouseClicked(evt);
            }
        });

        btTambahPegawai.setBackground(new java.awt.Color(65, 140, 105));
        btTambahPegawai.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btTambahPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btTambahPegawai.setText("Tambah Pegawai");
        btTambahPegawai.setBorderPainted(false);
        btTambahPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahPegawaiActionPerformed(evt);
            }
        });

        btEditPegawai.setBackground(new java.awt.Color(65, 140, 105));
        btEditPegawai.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btEditPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btEditPegawai.setText("Edit Pegawai");
        btEditPegawai.setBorderPainted(false);
        btEditPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEditPegawaiMouseClicked(evt);
            }
        });
        btEditPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditPegawaiActionPerformed(evt);
            }
        });

        btHapusKaryawan.setBackground(new java.awt.Color(65, 140, 105));
        btHapusKaryawan.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btHapusKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btHapusKaryawan.setText("Hapus Karyawan");
        btHapusKaryawan.setBorderPainted(false);
        btHapusKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHapusKaryawanMouseClicked(evt);
            }
        });
        btHapusKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusKaryawanActionPerformed(evt);
            }
        });

        btLogout.setBackground(new java.awt.Color(65, 140, 105));
        btLogout.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setText("Keluar");
        btLogout.setBorderPainted(false);
        btLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLogoutMouseClicked(evt);
            }
        });
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btAbout.setBackground(new java.awt.Color(65, 140, 105));
        btAbout.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btAbout.setForeground(new java.awt.Color(255, 255, 255));
        btAbout.setText("About");
        btAbout.setBorderPainted(false);
        btAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAboutMouseClicked(evt);
            }
        });
        btAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btTambahPegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditPegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btHapusKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btTambahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btEditPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btHapusKaryawan)
                .addGap(32, 32, 32)
                .addComponent(btAbout)
                .addGap(28, 28, 28)
                .addComponent(btLogout)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 650));

        tblKaryawan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 940, 130));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        txtId.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 250, -1));

        cbJabatan.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        cbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jabatan", "Direktur", "Admin", "Karyawan", "Manager Proyek", "Akunting", "Pemasaran", "Produksi", "IT Support", "Staf HR", " " }));
        getContentPane().add(cbJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 250, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel4.setText("Jabatan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        buttonGroup1.add(rbLakiLaki);
        rbLakiLaki.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbLakiLaki.setText("Laki-Laki");
        rbLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiLakiActionPerformed(evt);
            }
        });
        getContentPane().add(rbLakiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 240, -1));

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 250, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel8.setText("Tanggal Lahir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        txtTanggalLahir.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        txtTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalLahirActionPerformed(evt);
            }
        });
        getContentPane().add(txtTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 250, -1));

        txtNomorTelpon.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        getContentPane().add(txtNomorTelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 250, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("Nomor Telpon");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 630, -1, -1));

        btHapus.setBackground(new java.awt.Color(2, 112, 75));
        btHapus.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        btHapus.setForeground(new java.awt.Color(255, 255, 255));
        btHapus.setText("Hapus");
        btHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHapusMouseClicked(evt);
            }
        });
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 450, 210, 60));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel10.setText("Nama");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        txtNama.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 250, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 250, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFormLogin.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened
    
    
    private void btDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDashboardMouseClicked
        JFormAdmin adminFrame = new JFormAdmin();
        adminFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDashboardMouseClicked

    private void btTambahPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahPegawaiActionPerformed
        // TODO add your handling code here:
        JFormTambah tambahFrame = new JFormTambah();
        tambahFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btTambahPegawaiActionPerformed

    private void btEditPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditPegawaiActionPerformed

    private void rbLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiLakiActionPerformed

    private void txtTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalLahirActionPerformed

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
        // TODO add your handling code here:
         int baris = tblKaryawan.rowAtPoint(evt.getPoint());

    if (baris >= 0 && baris < tblKaryawan.getRowCount()) {
        String id = tblKaryawan.getValueAt(baris, 0).toString(); // Ubah indeks sesuai kebutuhan
        String nama = tblKaryawan.getValueAt(baris, 1).toString();
        String jabatan = tblKaryawan.getValueAt(baris, 2).toString();
        String alamat = tblKaryawan.getValueAt(baris, 3).toString();
        String tanggalLahir = tblKaryawan.getValueAt(baris, 4).toString();
        String jenisKelamin = tblKaryawan.getValueAt(baris, 5).toString();
        String nomorTelpon = tblKaryawan.getValueAt(baris, 6).toString();
        bersihkan();
        txtId.setText(id);
        txtNama.setText(nama);
    cbJabatan.setSelectedItem(jabatan);
    txtAlamat.setText(alamat);
    txtTanggalLahir.setText(tanggalLahir);

    // Mengatur radio button jenis kelamin sesuai nilai yang ada di tabel
    if ("Laki-laki".equals(jenisKelamin)) {
        rbLakiLaki.setSelected(true);
    } else if ("Perempuan".equals(jenisKelamin)) {
        rbPerempuan.setSelected(true);
    }

    // Mengatur nilai untuk nomor telpon
    txtNomorTelpon.setText(nomorTelpon);
    
    // Mengatur fokus ke komponen nama
    txtNama.requestFocus();
    }
    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void btHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHapusMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "delete from karyawan where id='"+txtId.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        bersihkan();
    }//GEN-LAST:event_btHapusMouseClicked

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btHapusActionPerformed

    private void btHapusKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHapusKaryawanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btHapusKaryawanMouseClicked

    private void btHapusKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHapusKaryawanActionPerformed

    private void btLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseClicked
        // TODO add your handling code here:
        JFormLogin loginFrame = new JFormLogin();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLogoutMouseClicked

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btEditPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditPegawaiMouseClicked
        // TODO add your handling code here:
        JFormEdit editFrame = new JFormEdit();
        editFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btEditPegawaiMouseClicked

    private void btAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAboutMouseClicked
        // TODO add your handling code here:
        JFormAbout aboutFrame = new JFormAbout();
        aboutFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAboutMouseClicked

    private void btAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAboutActionPerformed
    
    private void bersihkan(){
        txtId.setText(null);
        txtAlamat.setText(null);
        txtNama.setText(null);
        cbJabatan.setSelectedIndex(0);
        txtNomorTelpon.setText(null);
        txtTanggalLahir.setText(null);
        buttonGroup1.clearSelection();
        txtNama.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormHapus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbout;
    private javax.swing.JButton btDashboard;
    private javax.swing.JButton btEditPegawai;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btHapusKaryawan;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btTambahPegawai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbLakiLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomorTelpon;
    private javax.swing.JTextField txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
